RHS/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('User.urls')),
]

User/urls.py
from django.conf.urls import url
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'user'

urlpatterns = [
    url(r'^all/$', views.SnippetList.as_view(), name='snippet_list'),
    url(r'^snippet/(?P<pk>[0-9]+)/$', views.SnippetDetail.as_view(), name='snippet_detail'),
    url(r'^register/$', views.user_registration, name='user_registration'),
    url(r'^login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    url(r'^profile/$', views.user_profile, name='user_profile'),
    url(r'^add/patient/$', views.add_patient, name='add_patient'),
    url(r'^add/patient/detail/$', views.add_patient_detail, name='add_patient_detail'),
    url(r'^patient/(?P<username>[\w.@\-]+)/$', views.patient_profile, name='patient_profile'),
    url(r'^add/patient/current_status/(?P<username>[\w.@\-]+)/$', views.add_current_patient_status,
        name='add_patient_current_status'),
    url(r'^add/patient/medical_status/(?P<username>[\w.@\-]+)/$', views.add_patient_medical_status,
        name='add_patient_medical_status'),
    url(r'^add/patient/appointment/(?P<username>[\w.@\-]+)/$', views.appointment,
        name='appointment'),
]
urlpatterns = format_suffix_patterns(urlpatterns)

User/forms.py
from django import forms
from .models import *


class UserRegistrationForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['email', 'username', 'first_name', 'last_name', 'user_type', 'password']


class AddPatientForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['email', 'username', 'first_name', 'last_name', 'password']


class AddPatientDetailForm(forms.ModelForm):
    class Meta:
        model = PatientDetail
        exclude = ['patient']


class LoginForm(forms.Form):
    email = forms.EmailField(label='Email',
                             widget=forms.TextInput(attrs={'class': 'mdl-textfield__input', 'autocomplete': 'off'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'mdl-textfield__input'}))


class PatientHistoryForm(forms.ModelForm):
    class Meta:
        model = PatientHistory
        exclude = ['patient']


class CurrentPatientStatusForm(forms.ModelForm):
    class Meta:
        model = CurrentPatientStatus
        exclude = ['patient', 'care_provider', 'visit_date']


class PatientMedicalStatusForm(forms.ModelForm):
    class Meta:
        model = PatientMedicalStatus
        exclude = ['patient', 'care_provider', 'date']


class PatientDiagnosisForm(forms.ModelForm):
    class Meta:
        model = PatientDiagnosis
        exclude = ['patient', 'doctor', 'date']


class PatientMedicationForm(forms.ModelForm):
    class Meta:
        model = PatientMedication
        exclude = ['patient', 'doctor', 'date']

User/views.py
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from rest_framework import status
from rest_framework.authentication import SessionAuthentication, BasicAuthentication, TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import *
from .permissions import BlackListPermission
from .serializers import SnippetSerializer, CustomUserSerializer
from .appointment import doctor_appointment


# Create your views here.


class SnippetList(APIView):
    authentication_classes = (SessionAuthentication, BasicAuthentication, TokenAuthentication)
    permission_classes = (IsAuthenticated, BlackListPermission)

    def get(self, request, format=None):
        snippets = Snippets.objects.all()
        serializer = SnippetSerializer(snippets, many=True)
        return Response(serializer.data)

    def post(self, request, format=None):
        # data = JSONParser().parse(request)
        serializer = SnippetSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class SnippetDetail(APIView):
    def get_object(self, pk):
        try:
            return Snippets.objects.get(pk=pk)
        except Snippets.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)

    def get(self, request, pk, format=None):
        serializer = SnippetSerializer(self.get_object(pk))
        return Response(serializer.data)

    def put(self, request, pk, format=None):
        snippet = self.get_object(pk)
        serializer = SnippetSerializer(snippet, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        snippet = self.get_object(pk)
        snippet.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class UserRegistration(APIView):
    @staticmethod
    def post(request, format=None):
        serializer = CustomUserSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            username = serializer.validated_data['username']
            user = CustomUser.objects.get(username=username)
            token = Token.objects.get(user=user)
            return Response({'success': True, 'token': token.key}, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class UserLogin(APIView):
    # authentication_classes = (SessionAuthentication, BasicAuthentication, TokenAuthentication)

    def post(self, request, format=None):
        email = request.data['email']
        password = request.data['password']
        user = authenticate(email=email, password=password)
        if user is not None:
            token = Token.objects.get(user=user)
            return Response({"success": True, "token": token.key, "user_type": user.user_type},
                            status=status.HTTP_200_OK)
        else:
            return Response({"success": False}, status=status.HTTP_404_NOT_FOUND)


@login_required(login_url='user:user_login')
def user_registration(request):
    if check_superuser(request):
        if request.method == 'GET':
            form = UserRegistrationForm()
            return render(request, 'User/user-registration.html', {'form': form})
        elif request.method == 'POST':
            form = UserRegistrationForm(request.POST)
            if form.is_valid():
                user = form.save(commit=False)
                password = form.cleaned_data['password']
                user.set_password(password)
                user.save()
                return HttpResponse("Successfully Registered")

        else:
            return HttpResponse("Request type not supported")
    return HttpResponse("Not permitted to view this page")


def user_login(request):
    if request.method == 'GET':
        if request.user.is_authenticated():
            return redirect('user:user_profile')
        form = LoginForm()
        return render(request, 'User/user-login.html', {'form': form})
    elif request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(email=email, password=password)
            if user is not None:
                login(request, user)
                if request.GET.get('next'):
                    url = request.GET.get('next')
                    return redirect('user:user_registration')
                else:
                    return redirect('user:user_profile')
            else:
                return HttpResponse("Wrong Username or password")


@login_required(login_url='user:user_login')
def user_profile(request):
    if request.method == 'GET':
        if request.user.is_admin:
            return render(request, 'User/Profile/admin-profile.html')
        if request.user.user_type == 'CG':
            return render(request, 'User/Profile/caregiver-profile.html')
        elif request.user.user_type == 'DC':
            return render(request, 'User/Profile/doctor-profile.html')
        elif request.user.user_type == 'AD':
            return render(request, 'User/Profile/admin-profile.html')
    elif request.method == 'POST':
        if request.user.user_type == 'CG':
            try:
                patient = CustomUser.objects.get(username=request.POST.get('username'))
                if patient.user_type == 'P':
                    return render(request, 'User/Profile/caregiver-profile.html', {'patient': patient})
                else:
                    return render(request, 'User/Profile/caregiver-profile.html',
                                  {'error': 'No matching Patient Exist'})
            except CustomUser.DoesNotExist:
                return render(request, 'User/Profile/caregiver-profile.html', {'error': 'No matching Patient Exist'})


def user_logout(request):
    logout(request)
    return redirect('user:user_login')


@login_required(login_url='user:user_login')
def add_patient(request):
    if request.method == 'GET':
        form = AddPatientForm()
        return render(request, 'User/Profile/add-patient.html', {'form': form})
    elif request.method == 'POST':
        form = AddPatientForm(request.POST)
        if form.is_valid():
            patient = form.save(commit=False)
            patient.user_type = 'P'
            patient.save()
            request.session['patient_username'] = form.cleaned_data['username']
            return redirect('user:add_patient_detail')
        else:
            return HttpResponse('Invalid Form')


@login_required(login_url='user:user_login')
def add_patient_detail(request):
    username = request.session.get('patient_username', None)
    if username is not None:
        if request.method == 'GET':
            form = AddPatientDetailForm()
            return render(request, 'User/Profile/add-patient-detail.html', {'form': form})
        elif request.method == 'POST':
            form = AddPatientDetailForm(request.POST)
            if form.is_valid():
                patient_form = form.save(commit=False)
                patient = CustomUser.objects.get(username=username)
                patient_form.patient = patient
                patient_form.save()
                return HttpResponse("Successfully Added Patient")
            else:
                return HttpResponse("Invalid Form")

    else:
        return HttpResponse("Please add a patient first")


@login_required(login_url='user:user_login')
def patient_profile(request, username):
    patient = CustomUser.objects.get(username=username)
    try:
        current_patient_status = patient.currentpatientstatus
    except CurrentPatientStatus.DoesNotExist:
        current_patient_status = None
    patient_medical_status_list = patient.patientmedicalstatus_set.all().order_by('-date')
    if len(patient_medical_status_list) > 0:
        patient_medical_status = patient_medical_status_list[0]
    else:
        patient_medical_status = None
    patient_diagnosis_list = patient.patientdiagnosis_set.all().order_by('-date')
    if len(patient_diagnosis_list) > 0:
        patient_diagnosis = patient_diagnosis_list[0]
    else:
        patient_diagnosis = None

    return render(request, 'User/Profile/patient-profile.html',
                  {'user': request.user, 'patient': patient, 'current_patient_status': current_patient_status,
                   'patient_medical_status': patient_medical_status,
                   'patient_diagnosis': patient_diagnosis})


@login_required(login_url='user:user_login')
def add_current_patient_status(request, username):
    if request.method == 'GET':
        form = CurrentPatientStatusForm()
        return render(request, 'User/Profile/add-patient-status.html', {'form': form, 'username': username})
    elif request.method == 'POST':
        patient = CustomUser.objects.get(username=username)
        form = CurrentPatientStatusForm(request.POST)
        if form.is_valid():
            patient_form = form.save(commit=False)
            patient_form.patient = patient
            patient_form.care_provider = request.user
            patient_form.save()
            return HttpResponse("Done")
        else:
            return HttpResponse("Invalid Form")

User/templates/User/Profile/add-current-patient-status.html
{% extends 'User/Profile/base-profile.html' %}
{% block body %}
    <a href="{% url 'user:patient_profile' username %}">Back</a>
    <form method="post" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Done">
    </form>
{% endblock %}

User/templates/User/Profile/add-patient-detail.html
{% extends 'User/Profile/base-profile.html' %}
{% load staticfiles %}
{% block body %}
    <form method="post" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit">Add Patient</button>
    </form>
{% endblock %}

User/templates/User/Profile/add-patient-status.html
{% extends 'User/Profile/base-profile.html' %}
{% block body %}
    <a href="{% url 'user:patient_profile' username %}">Back</a>
    <form method="post" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Done">
    </form>
{% endblock %}

User/templates/User/Profile/add-patient.html
{% extends 'User/Profile/base-profile.html' %}
{% load staticfiles %}
{% block body %}
    <form method="post" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit">Add Patient Detail</button>
    </form>
{% endblock %}

User/templates/User/Profile/admin-profile.html
{% extends 'User/Profile/base-profile.html' %}
{% load staticfiles %}
{% block head %}{% endblock %}
{% block body %}
    <h1>Admin</h1>
    <a href="{% url 'user:user_registration' %}">Add Users</a>
{% endblock %}

User/templates/User/Profile/base-profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% block head %}{% endblock %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/flatly/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
</head>
<body>
<a href="{% url 'user:user_logout' %}">Logout</a>
{% block body %}{% endblock %}
</body>
</html>

User/templates/User/Profile/caregiver-profile.html
{% extends 'User/Profile/base-profile.html' %}
{% load staticfiles %}
{% block head %}{% endblock %}
{% block body %}
    <h1>Caregiver</h1>
    <a href="{% url 'user:add_patient' %}">Add Patient</a>
    <form method="post" action="">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Patient Username">
        <input type="submit" value="Search">
    </form>
    {% if patient %}
        <a href="{% url 'user:patient_profile' patient.username %}">{{ patient.get_full_name }}</a>
    {% endif %}
    {% if error %}
        <h3>{{ error }}</h3>
    {% endif %}
{% endblock %}

User/templates/User/Profile/doctor-profile.html
{% extends 'User/Profile/base-profile.html' %}
{% load staticfiles %}
{% block head %}{% endblock %}
{% block body %}
    <h1>Doctor</h1>
{% endblock %}

User/templates/User/Profile/patient-profile.html
{% extends 'User/base.html' %}
{% block body %}
    {% if user.user_type == 'CG' %}
        <h1>User is Caregiver</h1>
        <a href="{% url 'user:appointment' patient.username %}">Appoint Doctor</a>
    {% elif user.user_type == 'DC' %}
        <h1>User is Doctor</h1>
    {% endif %}
    <div class="row">
        <div class="col-md-6">
            <h1>Patient Details</h1>
            <h5>Full Name: {{ patient.get_full_name }}</h5>
            <h5>UHID Adhar Card: {{ patient.patientdetail.uhid }}</h5>
            <h5>Date of Birth: {{ patient.patientdetail.date_of_birth }}</h5>
            <h5>Gender: {{ patient.patientdetail.gender }}</h5>
            <h5>Age: {{ patient.patientdetail.age }}</h5>
            <h5>Occupation: {{ patient.patientdetail.occupation }}</h5>
            <h5>Address: {{ patient.patientdetail.address }}</h5>
            <h5>Locality: {{ patient.patientdetail.locality }}</h5>
        </div>

        <div class="col-md-6">
            {% if current_patient_status %}
                <h1>Patient Current Status</h1>
                <h5>Care Provider: {{ current_patient_status.care_provider.get_full_name }}</h5>
                <h5>Insurance Status: {{ current_patient_status.insurance_status }}</h5>
                <h5>Insurance ID: {{ current_patient_status.insurance_id }}</h5>
                <h5>Organ Donor Status: {{ current_patient_status.organ_donor_status }}</h5>
                <h5>Episode Type: {{ current_patient_status.episode_type }}</h5>
                <h5>Episode Number: {{ current_patient_status.episode_number }}</h5>
                <h5>Encounter Type: {{ current_patient_status.encounter_type }}</h5>
                <h5>Encounter Number: {{ current_patient_status.encounter_no }}</h5>
                <h5>Encounter Date: {{ current_patient_status.encounter_date_time }}</h5>
                <h5>Reason for visit: {{ current_patient_status.reason_for_visit }}</h5>
                <h5>Visit Date: {{ current_patient_status.visit_date }}</h5>
            {% else %}
                <a href="{% url 'user:add_patient_current_status' patient.username %}">Add Patient's Current Status</a>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            {% if patient_medical_status %}
                <h1>Patient Medical Status</h1>
                <h5>Care Provider: {{ patient_medical_status.care_provider.get_full_name }}</h5>
                <h5>Vitals Systolic BP: {{ patient_medical_status.vitals_systolic_BP }}</h5>
                <h5>Vitals Diastolic BP: {{ patient_medical_status.vitals_diastolic_BP }}</h5>
                <h5>Pulse Rate: {{ patient_medical_status.pulse_rate }}</h5>
                <h5>Temperature: {{ patient_medical_status.temperature }}</h5>
                <h5>Temperature Source: {{ patient_medical_status.temperature_source }}</h5>
                <h5>Respiration Rate: {{ patient_medical_status.respiration_rate }}</h5>
                <h5>Height (cm): {{ patient_medical_status.height }}</h5>
                <h5>Weight: {{ patient_medical_status.weight }}</h5>
                <h5>Blood Group: {{ patient_medical_status.blood_group }}</h5>
                <h5>Clinical Exam Observation: {{ patient_medical_status.clinical_exam_observation }}</h5>
                <h5>Investigation Result: {{ patient_medical_status.investigation_result }}</h5>
                <h5>Date of Input: {{ patient_medical_status.date }}</h5>
            {% else %}
                <a href="{% url 'user:add_patient_medical_status' patient.username %}">Add Patient Medical Status</a>
            {% endif %}
        </div>
        <div class="col-md-6">
            {% if patient_diagnosis %}
                <h1>Patient Diagnosis</h1>
                <h5>Doctor: {{ patient_diagnosis.doctor.get_full_name }}</h5>
                <h5>Diagnosis Type: {{ patient_diagnosis.diagnosis_type }}</h5>
                <h5>Diagnosis Code Name: {{ patient_diagnosis.diagnosis_code_name }}</h5>
                <h5>Diagnosis Code Code: {{ patient_diagnosis.diagnosis_code }}</h5>
                <h5>Diagnosis Description: {{ patient_diagnosis.diagnosis_description }}</h5>
                <h5>Treatment Plan Investigation: {{ patient_diagnosis.treatment_plan_investigations }}</h5>
                <h5>Treatment Plan Medication: {{ patient_diagnosis.treatment_plan_medication }}</h5>
                <h5>Treatment Plan Procdure: {{ patient_diagnosis.treatment_plan_procedure }}</h5>
                <h5>Treatment Plan Referral: {{ patient_diagnosis.treatment_plan_referral }}</h5>
                <h5>Other Treatment Plan Type: {{ patient_diagnosis.other_treatment_plan_type }}</h5>
                <h5>Current Critical Status: {{ patient_diagnosis.current_clinical_status }}</h5>
                <h5>Diagnosis Date: {{ patient_diagnosis.date }}</h5>
            {% else %}
                <h1>Patient not diagnosed yet</h1>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">

        </div>
    </div>
{% endblock %}